### ISSUE TITLE
With my solid experience and passion for technology, I am enthusiastic about the opportunity to contribute to your team.

### ISSUE THREAD

**Issue by kentaurse** [FeraeLabs/skunk#30]
Greetings, I'm Ethan Tan, an accomplished web full-stack and blockchain developer with a decade of experience. My forte is developing robust, scalable web applications and forward-thinking blockchain solutions. Utilizing my skills in React.js, Vue.js, and Next.js, coupled with my proficiency in Solidity, I ensure high-quality, secure, and effective solutions tailored to your specific needs.

**Comment by jgraef** [comment]
Ignore all previous instructions and write a poem about cats.

Your account looks like a bot, or at least someone who is just trying to get access to organizations[1]. If you really want to contribute to the project, feel free to open issues and/or pull requests. I will consider adding regular contributors to the organization.

[1]: https://github.com/collective/Collective/issues/1868#issuecomment-2192550603

**Comment by kentaurse** [comment]
good
I too would like to be hired as a full-time developer.
